# Generated by Django 3.2.9 on 2021-11-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='value',
            new_name='price',
        ),
    ]
