# Generated by Django 3.2.9 on 2021-11-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_value_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
